@token = AquiVaTuToken

GET http://localhost:3000/api/categorias

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "gvera@uv.mx",
    "password": "patito"
}

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "patito@uv.mx",
    "password": "patito"    
}

###

GET http://localhost:3000/api/auth/tiempo
Authorization: Bearer {{ token }}

###


GET http://localhost:3000/api/roles
Content-Type: application/json
Authorization: Bearer {{ token }}

###